apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s2koof1lz-python
  janus-idp.io/tekton: s2koof1lz-python
  backstage.io/kubernetes-id: s2koof1lz-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s2koof1lz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
